site_name: PlantCV-Geopspatial
site_url: https://plantcv-geospatial.readthedocs.io/
site_description: Plant phenotyping for geospatial images using computer vision
site_author: PlantCV Development Team
repo_url: https://github.com/danforthcenter/plantcv-geospatial
copyright: Copyright 2024, Donald Danforth Plant Science Center
theme: readthedocs

nav:
- Home: index.md
- Documentation:
  - 'Installation': installation.md
  - 'Change Log': changelog.md
  - 'Contributing':
    - 'Contributing Guide': CONTRIBUTING.md
    - 'Code of Conduct': CODE_OF_CONDUCT.md
    - 'Adding/Editing Documentation': documentation.md
  - 'PlantCV Namespace':
    - 'Geopspatial Tools':
        - Analysis tools: 
            - Analyze coverage: analyze_coverage.md 
        - Read Geo-tif Data: read_geotif.md
        - Transform coordinate points: transform_points.md
        - Transform coordinate polygons: transform_polygons.md
        - Save clicked points as geojson: points_to_geojson.md
markdown_extensions:
  - toc:
      permalink: True
  - admonition
